src/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', IndexView.as_view(), name='index'),
    path('account/change-email/', ChangeEmailView.as_view(), name='change-email'),
    path('account/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('account/change-personal-data/', ChangePersonalDataView.as_view(), name='change-personal-data'),
]

src/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('cookies/', views.CookiesView.as_view(), name='cookies'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
]

src/mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))), 
    path('accounts/', include('accounts.urls')),
    path('routes/', include('routes.urls')),
    path('', include('home.urls')),
]

handler400 = 'error.views.handle_bad_request_view'
handler403 = 'error.views.handle_permission_denied_view'
handler404 = 'error.views.handle_page_not_found_view'
handler500 = 'error.views.handle_server_error_view'

src/routes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'routes'
urlpatterns = [
    path('my-profile/', MyProfileView.as_view(), name='profile'),
    path('my-profile/tutorial/', AddRouteTutorialView.as_view(), name='tutorial'),
    path('my-profile/add-route/', AddRouteView.as_view(), name='add-route'),
    path('my-profile/my-comments/', MyCommentsView.as_view(), name='my-comments'),
    re_path(r'^my-profile/my-routes/edit-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        EditRouteFullView.as_view(), name='edit-route-full'),
    re_path(r'^my-profile/my-routes/edit_route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        EditRouteView.as_view(), name='edit-route'),
    re_path(r'^my-profile/my-routes/delete-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        DeleteRouteView.as_view(), name='delete-route'),
    re_path(r'^my-profile/my-routes/delete-route/(?P<route>\d+)/confirmed=(?P<confirmed>[^/]+)/next=(?P<next_url>.+)$', 
        DeleteRouteView.as_view(), name='delete-route'),
    re_path(r'^my-profile/my-routes/add-favorite-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddFavoriteRouteView.as_view(), name='add-favorite-route'),
    re_path(r'^my-profile/my-routes/delete-favorite-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        DeleteFavoriteRouteView.as_view(), name='delete-favorite-route'),
    re_path(r'^my-profile/my-routes/add-route-rate/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddRouteRateView.as_view(), name='add-route-rate'),
    re_path(r'^my-profile/my-routes/add-route-comment/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddRouteCommentView.as_view(), name='add-route-comment'),
    re_path(r'^my-profile/my-routes/add-comment-rate/(?P<comment>\d+)/(?P<rate>-?1)/next=(?P<next_url>.+)$', 
        AddCommentRateView.as_view(), name='add-comment-rate'),
    re_path(r'^my-profile/my-routes/(?:page/(?P<page_number>\d+)/)?$', 
        MyRoutesView.as_view(), name='my-routes'),
    re_path(r'^my-profile/my-routes/route-detail/(?P<route>\d+)/$', 
        MyRouteDetailView.as_view(), name='my-route-detail'),
    re_path(r'^my-profile/my-routes/route-weather/(?P<route>\d+)/$', 
        MyRouteWeatherView.as_view(), name='my-route-weather'),
    re_path(r'^my-profile/favorite-routes/(?:page/(?P<page_number>\d+)/)?$', 
        FavoriteRoutesView.as_view(), name='favorite-routes'),
    re_path(r'^my-profile/favorite-routes/route-detail/(?P<route>\d+)/$', 
        FavoriteRouteDetailView.as_view(), name='favorite-route-detail'),
    re_path(r'^my-profile/favorite-routes/route-weather/(?P<route>\d+)/$', 
        FavoriteRouteWeatherView.as_view(), name='favorite-route-weather'),
    re_path(r'^published-routes/(?:page/(?P<page_number>\d+)/)?$', 
        RoutesView.as_view(), name='routes'),
    re_path(r'^published-route-detail/(?P<route>\d+)/$', 
        RouteDetailView.as_view(), name='route-detail'),
    re_path(r'^published-route-weather/(?P<route>\d+)/$', 
        RouteWeatherView.as_view(), name='route-weather'),
    re_path(r'^search/(?:page/(?P<page_number>\d+)/)?$', 
        SearchRoutesView.as_view(), name='find'),
]

src/templates/base/footer.html
{% block footer %}     
    <footer id='page_footer'>
        <a href='{% url 'home:index' %}' class='footer_link'>Strona główna</a>
        <a href='{% url 'home:privacy' %}' class='footer_link'>Polityka prywatności</a>
        <a href='{% url 'home:cookies' %}' class='footer_link'>Polityka Cookies</a>
        <a href='{% url 'home:contact' %}' class='footer_link'>Kontakt</a>
        <a href='{% url 'home:about' %}' class='footer_link'>O nas</a>
        <div id='footer_copyright'></div>
    </footer>
{% endblock footer %}   

src/templates/base/index.html
<!DOCTYPE HTML>
<html lang='pl-PL'>
    <head>
        <title>{{ title }}ViRoutes</title> 
        <meta charset='utf-8'/>
        <meta name='author' content='Michał Dybaś'>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        {% load static %}                              
        <link rel='stylesheet' type='text/css' href='{% static 'css/base.css' %}'>      
        <link rel='stylesheet' type='text/css' href='{% static 'css/layout.css' %}'>    
        <link rel='stylesheet' type='text/css' href='{% static 'css/module.css' %}'>    
        <link rel='stylesheet' type='text/css' href='{% static 'css/state.css' %}'>     
        <link rel='stylesheet' type='text/css' href='{% static 'css/theme.css' %}'>
    </head>            
    <body>
        <div id='top'></div>
        {% block menu %}{% endblock menu %}             
        {% include 'base/menu.html' %} 

        <main id='page_main'>
            {% block content %} {% endblock content %} 
        </main>
        
        {% block footer %}{% endblock footer %}         
        {% include 'base/footer.html' %} 
        <a id='link_to_top' href='#top'><img id='link_to_top_img' src='{% static 'img/arrow_up_icon.png' %}'></a>
    </body>
    <script type='text/javascript' src='{% static 'js/base.js' %}'></script>
</html>

src/templates/base/menu.html
{% load static %}

{% block menu %}  
    <header id='page_header'>
        <div id='page_header_start'>
            <div class='page_header_icon_background' id='page_header_menu_button'>
                <img class='page_header_icon_img' src='{% static 'img/menu_icon.png' %}'>
            </div>
            <a href='{% url 'home:index' %}' id='page_header_home_logo_link'>
                <img id='page_header_home_logo_img' src='{% static 'img/menu_logo_icon.png' %}'>
            </a>
            <div id='page_header_collapsed_menu'>
                <div id='page_header_collapsed_menu_content'>
                    <div class='page_header_collapsed_menu_content_partition'></div>
                    <div>
                        <div class='page_header_collapsed_menu_content_description'></div> 
                            <a href='{% url 'home:index' %}' class='page_header_collapsed_menu_content_link'>Strona główna</a>
                            {% if not request.user.is_authenticated %}
                                <a href='{% url 'accounts:login' %}' class='page_header_collapsed_menu_content_link'>Zaloguj się</a>
                                <a href='{% url 'accounts:register' %}' class='page_header_collapsed_menu_content_link'>Zarejestruj się</a>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                                <a href='{% url 'accounts:index' %}' class='page_header_collapsed_menu_content_link'>Moje konto</a>
                                <a href='{% url 'accounts:logout' %}' class='page_header_collapsed_menu_content_link'>Wyloguj się</a>
                            {% endif %}
                            <div class='page_header_collapsed_menu_content_partition'></div>
                    </div>
                    <div>
                        <div class='page_header_collapsed_menu_content_description_dynamic'>
                        <div class='page_header_collapsed_menu_content_description_text'>Trasy</div>
                        <img class='page_header_collapsed_menu_content_description_arrow' src='{% static 'img/arrow_menu_icon.png' %}'>
                        </div> 
                        <a href='{% url 'routes:routes' %}' class='page_header_collapsed_menu_content_link'>Wszystkie trasy</a>
                        <a href='{% url 'routes:find' %}' class='page_header_collapsed_menu_content_link'>Wyszukaj trasę</a>
                        <div class='page_header_collapsed_menu_content_partition'></div>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div>
                            <div class='page_header_collapsed_menu_content_description_dynamic'>
                            <div class='page_header_collapsed_menu_content_description_text'>Mój Profil</div>
                            <img class='page_header_collapsed_menu_content_description_arrow' src='{% static 'img/arrow_menu_icon.png' %}'>
                            </div>
                            <a href='{% url 'routes:profile' %}' class='page_header_collapsed_menu_content_link'>Mój profil</a>
                            <a href='{% url 'routes:add-route' %}' class='page_header_collapsed_menu_content_link'>Dodaj trasę</a>
                            <a href='{% url 'routes:tutorial' %}' class='page_header_collapsed_menu_content_link'>Poradnik wyznaczania trasy</a>
                            <a href='{% url 'routes:my-routes' %}' class='page_header_collapsed_menu_content_link'>Moje trasy</a>
                            <a href='{% url 'routes:my-comments' %}' class='page_header_collapsed_menu_content_link'>Moje komentarze</a>
                            <a href='{% url 'routes:favorite-routes' %}' class='page_header_collapsed_menu_content_link'>Ulubione trasy</a>
                            <div class='page_header_collapsed_menu_content_partition'></div>
                        </div>
                    {% endif %}
                    <div>
                            <div class='page_header_collapsed_menu_content_description_dynamic'>
                            <div class='page_header_collapsed_menu_content_description_text'>WIĘCEJ</div>
                            <img class='page_header_collapsed_menu_content_description_arrow' src='{% static 'img/arrow_menu_icon.png' %}'>
                            </div> 
                                <a href='{% url 'home:privacy' %}' class='page_header_collapsed_menu_content_link'>Polityka prywatności</a>
                                <a href='{% url 'home:cookies' %}' class='page_header_collapsed_menu_content_link'>Polityka Cookies</a>
                                <a href='{% url 'home:contact' %}' class='page_header_collapsed_menu_content_link'>Kontakt</a>
                                <a href='{% url 'home:about' %}' class='page_header_collapsed_menu_content_link'>O nas</a>
                            <div class='page_header_collapsed_menu_content_partition'></div>
                    </div>
                </div>
            </div>
        </div>
        <div id='page_header_clock'></div>
        <div id='page_header_end'>
            {% if not request.user.is_authenticated %}
                <a href='{% url 'accounts:login' %}' class='page_header_icon_background'>
                    <img class='page_header_icon_img' src='{% static 'img/log_in_icon.png' %}'>
                    <div class='page_header_link_description'>Zaloguj</div>
                </a>
            {% endif %}
            {% if request.user.is_authenticated %}
                <a href='{% url 'accounts:index' %}' class='page_header_icon_background'>
                    <img class='page_header_icon_img' src='{% static 'img/settings_icon.png' %}'>
                    <div class='page_header_link_description'>Konto</div>
                </a>
                <a href='{% url 'accounts:logout' %}' class='page_header_icon_background'>
                    <img class='page_header_icon_img' src='{% static 'img/log_out_icon.png' %}'>
                    <div class='page_header_link_description'>Wyloguj</div>
                </a>
            {% endif %}
        </div>
    </header>
{% endblock menu %}