src/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('cookies/', views.CookiesView.as_view(), name='cookies'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
]

src/mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))), 
    path('accounts/', include('accounts.urls')),
    path('routes/', include('routes.urls')),
    path('', include('home.urls')),
]

handler400 = 'error.views.handle_bad_request_view'
handler403 = 'error.views.handle_permission_denied_view'
handler404 = 'error.views.handle_page_not_found_view'
handler500 = 'error.views.handle_server_error_view'

src/routes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'routes'
urlpatterns = [
    path('my-profile/', MyProfileView.as_view(), name='profile'),
    path('my-profile/tutorial/', AddRouteTutorialView.as_view(), name='tutorial'),
    path('my-profile/add-route/', AddRouteView.as_view(), name='add-route'),
    path('my-profile/my-comments/', MyCommentsView.as_view(), name='my-comments'),
    re_path(r'^my-profile/my-routes/edit-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        EditRouteFullView.as_view(), name='edit-route-full'),
    re_path(r'^my-profile/my-routes/edit_route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        EditRouteView.as_view(), name='edit-route'),
    re_path(r'^my-profile/my-routes/delete-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        DeleteRouteView.as_view(), name='delete-route'),
    re_path(r'^my-profile/my-routes/delete-route/(?P<route>\d+)/confirmed=(?P<confirmed>[^/]+)/next=(?P<next_url>.+)$', 
        DeleteRouteView.as_view(), name='delete-route'),
    re_path(r'^my-profile/my-routes/add-favorite-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddFavoriteRouteView.as_view(), name='add-favorite-route'),
    re_path(r'^my-profile/my-routes/delete-favorite-route/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        DeleteFavoriteRouteView.as_view(), name='delete-favorite-route'),
    re_path(r'^my-profile/my-routes/add-route-rate/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddRouteRateView.as_view(), name='add-route-rate'),
    re_path(r'^my-profile/my-routes/add-route-comment/(?P<route>\d+)/next=(?P<next_url>.+)$', 
        AddRouteCommentView.as_view(), name='add-route-comment'),
    re_path(r'^my-profile/my-routes/add-comment-rate/(?P<comment>\d+)/(?P<rate>-?1)/next=(?P<next_url>.+)$', 
        AddCommentRateView.as_view(), name='add-comment-rate'),
    re_path(r'^my-profile/my-routes/(?:page/(?P<page_number>\d+)/)?$', 
        MyRoutesView.as_view(), name='my-routes'),
    re_path(r'^my-profile/my-routes/route-detail/(?P<route>\d+)/$', 
        MyRouteDetailView.as_view(), name='my-route-detail'),
    re_path(r'^my-profile/my-routes/route-weather/(?P<route>\d+)/$', 
        MyRouteWeatherView.as_view(), name='my-route-weather'),
    re_path(r'^my-profile/favorite-routes/(?:page/(?P<page_number>\d+)/)?$', 
        FavoriteRoutesView.as_view(), name='favorite-routes'),
    re_path(r'^my-profile/favorite-routes/route-detail/(?P<route>\d+)/$', 
        FavoriteRouteDetailView.as_view(), name='favorite-route-detail'),
    re_path(r'^my-profile/favorite-routes/route-weather/(?P<route>\d+)/$', 
        FavoriteRouteWeatherView.as_view(), name='favorite-route-weather'),
    re_path(r'^published-routes/(?:page/(?P<page_number>\d+)/)?$', 
        RoutesView.as_view(), name='routes'),
    re_path(r'^published-route-detail/(?P<route>\d+)/$', 
        RouteDetailView.as_view(), name='route-detail'),
    re_path(r'^published-route-weather/(?P<route>\d+)/$', 
        RouteWeatherView.as_view(), name='route-weather'),
    re_path(r'^search/(?:page/(?P<page_number>\d+)/)?$', 
        SearchRoutesView.as_view(), name='find'),
]

src/routes/models.py
from datetime import time
import re
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from mySite import settings
from django.db.models import Avg, Count
import requests

ROUTE_RATE_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]

COMMENT_RATE_CHOICES = [
        (-1, '-1'),
        (1, '1'),
    ]

class CustomValidator():
    def validate_route_url(value):
        if re.search('^(https://)?maps.openrouteservice.org/#/.*$', value) == None:
            raise ValidationError('Podany adres url jest nieprawidłowy.')
        if re.search('^(https://)?maps.openrouteservice.org/#/directions/'
            + '([^/]+/){2}(^/]+/)*data/([0-9]+,)*[0-9]+$', value) == None:
            raise ValidationError('Podana trasa jest nieprawidłowa.')
        if re.search('null', value) != None:
            raise ValidationError('Trasa nie może zawierać pustego punktu.')
        if re.search('Your%20location', value) != None:
            raise ValidationError('Trasa nie może zawierać jako punktu aktualnej lokalizacji.')

class Route(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Użytkownik:')
    url = models.TextField(verbose_name='Adres url trasy:', null=False, blank=False, validators=[CustomValidator.validate_route_url])
    name = models.CharField(verbose_name='Nazwa trasy:', null=False, blank=False, max_length=100)
    description = models.TextField(verbose_name='Opis trasy:', null=True, blank=True)
    is_published = models.BooleanField(verbose_name='Opublikować?', null=False, blank=False, default=False)
    is_deleted = models.BooleanField(verbose_name='Usunąć?', null=False, blank=False, default=False)
    date_published = models.DateTimeField(verbose_name='Data publikacji:', null=True, blank=True, editable=False)
    date_created = models.DateTimeField(verbose_name='Data utworzenia:', null=False, blank=False, editable=False)
    last_modyfied = models.DateTimeField(verbose_name='Data modyfikacji:', null=True, blank=True)

    class Meta:
        verbose_name = "Trasa"
        verbose_name_plural = "Trasy"
        get_latest_by = '-date_created'
        unique_together = [['created_by', 'name']]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = timezone.now()
        self.last_modyfied = timezone.now()
        if self.date_published == None and self.is_published == True:
            self.date_published = timezone.now()
        return super(Route, self).save(*args, **kwargs)

    def avgRate(self):
        rate = RouteRate.objects.filter(referenced_route=self.id, is_deleted=False).aggregate(Avg('rate'))
        rate = rate['rate__avg']
        if rate != None:
            rate = '{:.1f}'.format(rate)
        else:
            rate = 'Brak ocen'
        return rate

    def isLiked(self, *args):
        liked = FavoriteRoute.objects.filter(created_by=args[0], referenced_route=self.id, is_deleted=False)
    
        if len(liked) > 0:
            return True
        else:
            return False

    def getWaypoints(self):
        url = ''
        waypoints = re.split('(https://)?maps.openrouteservice.org/#/directions/', self.url)
        if len(waypoints) == 3:
            url = waypoints[2]
        else:
            url = waypoints[1]
        waypoints = re.split('/data/', url)
        url = waypoints[0]
        waypoints = re.sub('/', '|', url)
        return waypoints

    def getWeather(self, waypoints):
        url = "https://visual-crossing-weather.p.rapidapi.com/forecast"
        querystring = {"aggregateHours":"24","location":waypoints,"contentType":"json","unitGroup":"metric",
            "shortColumnNames":"True", 'forecastDays': 7, 'extendedStats': "True"}

        headers = {
            'x-rapidapi-host': "visual-crossing-weather.p.rapidapi.com",
            'x-rapidapi-key': settings.x_rapidapi_key
        }
        response = requests.request("GET", url, headers=headers, params=querystring)
        if not 'locations' in response.json():
            return None
        else:
            response = response.json()['locations']
        return response

class FavoriteRoute(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Użytkownik:')
    referenced_route = models.ForeignKey(Route, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Trasa:')
    is_deleted = models.BooleanField(verbose_name='Usunąć?', null=False, blank=False, default=False)
    date_created = models.DateTimeField(verbose_name='Data utworzenia:', null=False, blank=False, editable=False)
    last_modyfied = models.DateTimeField(verbose_name='Data modyfikacji:', null=True, blank=True)

    class Meta:
        verbose_name = "Ulubiona trasa"
        verbose_name_plural = "Ulubione trasy"
        get_latest_by = '-date_created'
        unique_together = [['created_by', 'referenced_route']]
        
    def __str__(self):
        return self.referenced_route.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = timezone.now()
        self.last_modyfied = timezone.now()
        return super(FavoriteRoute, self).save(*args, **kwargs)

class RouteRate(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Użytkownik:')
    referenced_route = models.ForeignKey(Route, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Trasa:')
    rate = models.IntegerField(verbose_name='Ocena:', null=False, blank=False, choices=ROUTE_RATE_CHOICES, default=5)
    is_deleted = models.BooleanField(verbose_name='Usunąć?', null=False, blank=False, default=False)
    date_created = models.DateTimeField(verbose_name='Data utworzenia:', null=False, blank=False, editable=False)
    last_modyfied = models.DateTimeField(verbose_name='Data modyfikacji:', null=True, blank=True)

    class Meta: 
        verbose_name = "Ocena trasy"
        verbose_name_plural = "Oceny tras"
        get_latest_by = '-date_created'
        unique_together = [['created_by', 'referenced_route']]

    def __str__(self):
        return str(self.created_by.username) + ' - ' + str(self.referenced_route.name) + ' - ' +  str(self.rate)

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = timezone.now()
        self.last_modyfied = timezone.now()
        return super(RouteRate, self).save(*args, **kwargs)

class Comment(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Użytkownik:')
    referenced_route = models.ForeignKey(Route, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Trasa:')
    content = models.TextField(verbose_name='Treść komentarza:', null=False, blank=False)
    is_deleted = models.BooleanField(verbose_name='Usunąć?', null=False, blank=False, default=False)
    date_created = models.DateTimeField(verbose_name='Data utworzenia:', null=False, blank=False, editable=False)
    last_modyfied = models.DateTimeField(verbose_name='Data modyfikacji:', null=True, blank=True)

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"
        get_latest_by = '-date_created'

    def __str__(self):
        return self.content

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = timezone.now()
        self.last_modyfied = timezone.now()
        return super(Comment, self).save(*args, **kwargs)

    def sumRate(self, *args, **kwargs):
        goodRate = CommentRate.objects.filter(referenced_comment=self.id, is_deleted=False, rate=1).aggregate(Count('rate'))
        badRate = CommentRate.objects.filter(referenced_comment=self.id, is_deleted=False, rate=-1).aggregate(Count('rate'))
        goodRate = goodRate['rate__count']
        badRate = badRate['rate__count']
        return goodRate - badRate

class CommentRate(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Użytkownik:')
    referenced_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Komentarz:')
    rate = models.IntegerField(verbose_name='Ocena:', null=False, blank=False, choices=COMMENT_RATE_CHOICES, default=1)
    is_deleted = models.BooleanField(verbose_name='Usunąć?', null=False, blank=False, default=False)
    date_created = models.DateTimeField(verbose_name='Data utworzenia:', null=False, blank=False, editable=False)
    last_modyfied = models.DateTimeField(verbose_name='Data modyfikacji:', null=True, blank=True)

    class Meta: 
        verbose_name = "Ocena komentarza"
        verbose_name_plural = "Oceny komentarzy"
        get_latest_by = '-date_created'
        unique_together = [['created_by', 'referenced_comment']]

    def __str__(self):
        return str(self.created_by.username) + ' - ' + str(self.referenced_comment.id) + ' - ' +  str(self.rate)

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = timezone.now()
        self.last_modyfied = timezone.now()
        return super(CommentRate, self).save(*args, **kwargs)

src/routes/forms.py
from dataclasses import fields
from random import choices
from tabnanny import verbose
from django import forms
from .models import Comment, Route, RouteRate

class AddRouteForm(forms.ModelForm):
    is_published = forms.ChoiceField(label='Opublikować', required=True, 
        help_text='Opublikowanie trasy wiąże się z udostępnieniem jej innym użytkownikom'
            + ' i zablokowaniem edycji trasy.', choices=((False, 'Nie'), (True, 'Tak')))
    class Meta:
        model = Route
        exclude = ['created_by', 'is_deleted', 'date_published', 'last_modyfied']

class EditRouteFullForm(forms.ModelForm):
    is_published = forms.ChoiceField(label='Opublikować', required=True, 
    help_text='Opublikowanie trasy wiąże się z udostępnieniem jej innym użytkownikom'
        + ' i zablokowaniem edycji trasy.', choices=((False, 'Nie'), (True, 'Tak')))
    class Meta:
        model = Route
        exclude = ['created_by', 'is_deleted', 'date_published', 'last_modyfied']

class EditRouteForm(forms.ModelForm):
    class Meta:
        model = Route
        exclude = ['url', 'is_published', 'created_by', 'is_deleted', 'date_published', 'last_modyfied']

class RouteRateForm(forms.ModelForm):
    class Meta:
        model=RouteRate
        fields = ['rate']

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']

class SearchForm(forms.Form):
    name = forms.CharField(label='Nazwa trasy:', required=False, max_length=150)
    author = forms.CharField(label='Autor trasy:', required=False, max_length=150)
    date = forms.DateField(label='Data publikacji:', required=False, 
        widget=forms.DateInput(attrs={'type': 'date'}))
    datetype = forms.ChoiceField(label='^Data', required=False, 
        choices=((1, 'Młodsza'), (2, 'Starsza')))
    sort = forms.ChoiceField(label='Sortuj według', required=False, 
        choices=((1, 'Daty publikacji'), (2, 'Nazwy trasy'), (3, 'Autora trasy')))
    sorttype = forms.ChoiceField(label='^Typ sortowania', required=False, 
        choices=((1, 'Malejący'), (2, 'Rosnący')))

src/routes/admin.py
from django.contrib import admin
from . import models

admin.site.register(models.Route)
admin.site.register(models.FavoriteRoute)
admin.site.register(models.RouteRate)
admin.site.register(models.Comment)
admin.site.register(models.CommentRate)

src/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'
    verbose_name = 'Trasy'

src/routes/tests.py
from django.test import TestCase

src/routes/templates/routes/edit-route.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        {% include 'routes/link/profile.html' %}
        {% include 'routes/link/my-routes.html' %}
        <span class='nav_text'>Edytuj trasę</span>
    </nav>
    <div class='flex-100'>
        <h1>Edytuj trasę</h1>
        <h2>Wprowadź dane trasy</h2>
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <p class='info'>{{ message }}</p>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <p class='error'>{{ message }}</p>
        {% else %}
            <p>{{ message }}</p>
        {% endif %}
    {% endfor %}
    </div>
    <div class='flex-100'>
    <form class='my_form' action='{% url 'routes:edit-route' route=route next_url=next_url %}' method='POST'>
        {% csrf_token %}

        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Zapisz zmiany'></p>
    </form>
    </div>
{% endblock content %}

src/routes/templates/routes/my-routes.html
{% extends 'base/index.html' %} 
{% load my_templatetag %}

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        {% include 'routes/link/profile.html' %}
        <span class='nav_text'>Moje trasy</span>
    </nav>

    <div class='flex-100'>
    <h1 >Moje trasy</h1>
    <h3><a href='{% url 'routes:add-route' %}'>Dodaj nową trasę</a></h3>
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <p class='info'>{{ message }}</p>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <p class='error'>{{ message }}</p>
        {% else %}
            <p>{{ message }}</p>
        {% endif %}
    {% endfor %}
    </div>

    <div class='flex-row flex-100'>
        <table class='flex-100'>

        <tr class='my_tr flex-row my_table info'>
            <th class='my_td flex-1'>Nazwa trasy</th>
            <th class='my_td flex-1'>Autor</th>
            <th class='my_td flex-1'>Ocena</th>
            <th class='my_td flex-1'>Data utworzenia</th>
            <th class='my_td flex-1'>Data publikacji</th>
            <th class='my_td flex-100' style='text-align:left;'>Opis trasy</th>
        </tr>

        {% for route in page_routes  %}

        <tr class='flex-100 my-td'>
            <td>
                <form class='flex-100 small_submit_button' action='{% url 'routes:add-route-rate' route=route.id next_url=request.path %}' method='POST'>
                    {% csrf_token %}
                    <label for="{{ form.rate.id_for_label }}">Dodaj ocenę:</label>
                    {{ form.rate }}
                    <input id='submit' type='submit' value='Oceń'>
                </form>
            </td>
        </tr>

        <tr class='my_tr flex-row my_table'>
            <td class='my_td flex-1 text-center'>{{route.name}}</td>
            <td class='my_td flex-1 text-center'>{{route.created_by.username}}</td>
            <td class='my_td flex-1 text-center'>{{route.avgRate}}</td>
            <td class='my_td flex-1 text-center'>{{route.date_created|date:"j E Y"}}</td>
            {% if route.date_published == None %}
                <td class='my_td flex-1 text-center'>Nie opublikowano</td>
            {% else %}
                <td class='my_td flex-1 text-center'>{{route.date_published|date:"j E Y"}}</td>
            {% endif %}
            {% if route.description|length < 1 %}
                <td class='my_td flex-100'>Brak opisu</td>
            {% elif route.description|length > 100 %}
            <td class='my_td flex-100'>{{route.description|truncatechars:100}}</td>
            {% else %}
                <td class='my_td flex-100'>{{route.description}}</td>
            {% endif %}
            
            <td class='my_td flex-100' style='text-align:center;'>
                <a href='{% url 'routes:my-route-detail' route=route.id %}' style='padding: 0 3px 0 3px;'>Szczegóły trasy</a>
                <a href='{% url 'routes:my-route-weather' route=route.id %}' style='padding: 0 3px 0 3px;'>Prognoza pogody</a>
                {% call_method route 'isLiked' request.user.id as liked %}
                {% if liked %}
                    <a href='{% url 'routes:delete-favorite-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Usuń z ulubionych</a>
                {% else %}
                    <a href='{% url 'routes:add-favorite-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Dodaj do ulubionych</a>
                {% endif %}
                {% if route.created_by == request.user %}
                    {% if route.is_published == True %}
                        <a href='{% url 'routes:edit-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Edytuj trasę</a>
                    {% else %}
                        <a href='{% url 'routes:edit-route-full' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Edytuj trasę</a>
                        <a href='{% url 'routes:delete-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Usuń trasę</a>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        </div>
        {% empty %}
            <tr class='my_tr flex-row my_table'>
                <td class='my_td flex-100 text-center'>Lista jest pusta</td>
            </tr>
        {% endfor %}
        </table>
    </div>

    <div class='flex-row flex-100 flex-justify-center flex-align-center' style='margin-top:auto;'>
        <div class='flex-100' style='text-align:center;'>Strona {{ current_page }} / {{ full_pages}}</div>
        <a href='{% url 'routes:my-routes'%}page/{{ previous_page }}'><button class='change_page_button'>{{ '<' }} Poprzednia</button></a>
        <a href='{% url 'routes:my-routes'%}page/{{ next_page }}'><button class='change_page_button'>Następna {{ '>' }} </button></a>
    </div>
{% endblock content %}

src/routes/templates/routes/published-routes.html
{% extends 'base/index.html' %} 
{% load my_templatetag %}

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        <span class='nav_text'>Opublikowane trasy</span>
    </nav>

    <div class='flex-100'>
    <h1 >Opublikowane trasy</h1>
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <p class='info'>{{ message }}</p>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <p class='error'>{{ message }}</p>
        {% else %}
            <p>{{ message }}</p>
        {% endif %}
    {% endfor %}
    </div>

    <div class='flex-row flex-100'>
        <table class='flex-100'>

        <tr class='my_tr flex-row my_table info'>
            <th class='my_td flex-1'>Nazwa trasy</th>
            <th class='my_td flex-1'>Autor</th>
            <th class='my_td flex-1'>Ocena</th>
            <th class='my_td flex-1'>Data utworzenia</th>
            <th class='my_td flex-1'>Data publikacji</th>
            <th class='my_td flex-100' style='text-align:left;'>Opis trasy</th>
        </tr>

        {% for route in page_routes  %}

        <tr class='flex-100 my-td'>
            <td>
                <form class='flex-100 small_submit_button' action='{% url 'routes:add-route-rate' route=route.id next_url=request.path %}' method='POST'>
                    {% csrf_token %}
                    <label for="{{ form.rate.id_for_label }}">Dodaj ocenę:</label>
                    {{ form.rate }}
                    <input id='submit' type='submit' value='Oceń'>
                </form>
            </td>
        </tr>


        <tr class='my_tr flex-row my_table'>
            <td class='my_td flex-1 text-center'>{{route.name}}</td>
            <td class='my_td flex-1 text-center'>{{route.created_by.username}}</td>
            <td class='my_td flex-1 text-center'>{{route.avgRate}}</td>
            <td class='my_td flex-1 text-center'>{{route.date_created|date:"j E Y"}}</td>
            {% if route.date_published == None %}
                <td class='my_td flex-1 text-center'>Nie opublikowano</td>
            {% else %}
                <td class='my_td flex-1 text-center'>{{route.date_published|date:"j E Y"}}</td>
            {% endif %}
            {% if route.description|length < 1 %}
                <td class='my_td flex-100'>Brak opisu</td>
            {% elif route.description|length > 100 %}
            <td class='my_td flex-100'>{{route.description|truncatechars:100}}</td>
            {% else %}
                <td class='my_td flex-100'>{{route.description}}</td>
            {% endif %}
            
            <td class='my_td flex-100' style='text-align:center;'>
                <a href='{% url 'routes:route-detail' route=route.id %}' style='padding: 0 3px 0 3px;'>Szczegóły trasy</a>
                <a href='{% url 'routes:route-weather' route=route.id %}' style='padding: 0 3px 0 3px;'>Prognoza pogody</a>
                {% if request.user.is_authenticated %}
                    {% call_method route 'isLiked' request.user.id as liked %}
                    {% if liked %}
                        <a href='{% url 'routes:delete-favorite-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Usuń z ulubionych</a>
                    {% else %}
                        <a href='{% url 'routes:add-favorite-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Dodaj do ulubionych</a>
                    {% endif %}
                    {% if route.created_by == request.user %}
                        {% if route.is_published == True %}
                            <a href='{% url 'routes:edit-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Edytuj trasę</a>
                        {% else %}
                            <a href='{% url 'routes:edit-route-full' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Edytuj trasę</a>
                            <a href='{% url 'routes:delete-route' route=route.id next_url=request.path %}' style='padding: 0 3px 0 3px;'>Usuń trasę</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        </div>
        {% empty %}
            <tr class='my_tr flex-row my_table'>
                <td class='my_td flex-100 text-center'>Lista jest pusta</td>
            </tr>
        {% endfor %}
        </table>
    </div>

    <div class='flex-row flex-100 flex-justify-center flex-align-center' style='margin-top:auto;'>
        <div class='flex-100' style='text-align:center;'>Strona {{ current_page }} / {{ full_pages}}</div>
        <a href='{% url 'routes:routes'%}page/{{ previous_page }}'><button class='change_page_button'>{{ '<' }} Poprzednia</button></a>
        <a href='{% url 'routes:routes'%}page/{{ next_page }}'><button class='change_page_button'>Następna {{ '>' }} </button></a>
    </div>
{% endblock content %}