src/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', IndexView.as_view(), name='index'),
    path('account/change-email/', ChangeEmailView.as_view(), name='change-email'),
    path('account/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('account/change-personal-data/', ChangePersonalDataView.as_view(), name='change-personal-data'),
]

src/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('cookies/', views.CookiesView.as_view(), name='cookies'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
]

src/mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))), 
    path('accounts/', include('accounts.urls')),
    path('routes/', include('routes.urls')),
    path('', include('home.urls')),
]

handler400 = 'error.views.handle_bad_request_view'
handler403 = 'error.views.handle_permission_denied_view'
handler404 = 'error.views.handle_page_not_found_view'
handler500 = 'error.views.handle_server_error_view'

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    REQUIRED_FIELDS = ['email']
    pass

User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False

src/accounts/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth import authenticate
from .models import User
from mySite import settings
from django.contrib.auth import password_validation

class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(label='*Użytkownik:', required=True, max_length=150, validators=[User.username_validator])
    first_name = forms.CharField(label='Imię:', max_length=150, required=False)
    last_name = forms.CharField(label='Nazwisko:', max_length=150, required=False)
    email = forms.EmailField(label='*Email:', required=True)
    password = forms.CharField(label='*Hasło:', required=True, widget=widgets.PasswordInput)
    confirmPassword = forms.CharField(label='*Potwierdź hasło:', required=True, widget=widgets.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'confirmPassword']

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        confirmPassword = self.cleaned_data.get('confirmPassword')
        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError('Podana nazwa użytkownika jest już zajęta.')

        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError('Podany adres email jest już zajęty.')

        if password != confirmPassword:
            raise forms.ValidationError('Podane hasło nie zgadza się z polem potwierdź hasło.')
        try:
            password_validation.validate_password(password, self.instance)
        except forms.ValidationError as error:
            self.add_error('password', error)
        return super(UserRegisterForm, self).clean(*args, **kwargs)

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Użytkownik:', required=True)
    password = forms.CharField(label='Hasło:', required=True, widget=widgets.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('Nazwa użytkownika albo hasło nieprawidłowe.')
            if not user.is_active:
                raise forms.ValidationError('Konto tego użytkownika nie jest aktywne.')
            return super(UserLoginForm, self).clean(*args, **kwargs)

class UserChangeEmailForm(forms.Form):
    email = forms.fields.EmailField(label='Nowy email:', required=True)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserChangeEmailForm, self).__init__(*args, **kwargs)

    def clean(self ,*args, **kwargs):
        email = self.cleaned_data['email']

        if email != self.request.user.email:
            email_qs = User.objects.filter(email=email)
            if email_qs.exists():
                raise forms.ValidationError('Podany adres email jest już zajęty.')
        return super(UserChangeEmailForm, self).clean(*args, **kwargs)

class UserChangePasswordForm(forms.Form):
    oldPassword = forms.CharField(label='Stare hasło:', required=True, widget=forms.widgets.PasswordInput)
    newPassword = forms.CharField(label='Nowe hasło:', required=True, widget=forms.widgets.PasswordInput)
    newPasswordConfirm = forms.CharField(label='Potwierdź nowe hasło:', required=True, widget=forms.widgets.PasswordInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self ,*args, **kwargs):
        oldPassword = self.cleaned_data['oldPassword']
        newPassword = self.cleaned_data['newPassword']
        newPasswordConfirm = self.cleaned_data['newPasswordConfirm']

        user = User.objects.get(username = self.request.user.username)
        if not user.check_password(oldPassword):
            self.add_error('oldPassword', 'Stare hasło jest nie prawidłowe.')

        if newPassword != newPasswordConfirm:
            raise forms.ValidationError('Podane nowe hasło nie zgadza się z polem potwierdź nowe hasło.')
        try:
            password_validation.validate_password(newPassword)
        except forms.ValidationError as error:
            self.add_error('newPassword', error)
        return super(UserChangePasswordForm, self).clean(*args, **kwargs)

class UserChangePersonalDataForm(forms.Form):
    first_name = forms.fields.CharField(label='Imię:', max_length=150, required=False)
    last_name = forms.fields.CharField(label='Nazwisko:', max_length=150, required=False)

src/accounts/views.py
from django.shortcuts import redirect, render
from django.views import View
from.forms import UserChangePasswordForm, UserLoginForm, UserRegisterForm, UserChangeEmailForm, UserChangePersonalDataForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User

class RegisterView(View):
    template_name = 'accounts/register.html'   
    title = 'Rejestracja | '                       
    form = UserRegisterForm()          

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:index')
        return render(request, self.template_name, {'title': self.title, 'form': self.form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:index')
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            login(request, user)
            return redirect('home:index')
        else:
            return render(request, self.template_name, {'title': self.title, 'form': form})

class LoginView(View):
    template_name = 'accounts/login.html'   
    title = 'Logowanie | '        
    form = UserLoginForm()            

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:index')
        return render(request, self.template_name, {'title': self.title, 'form': self.form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:index')
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            next = request.GET.get('next')
            login(request, user)
            if next:
                return redirect(next)
            else:
                return redirect('home:index')
        else:
            return render(request, self.template_name, {'title': self.title, 'form': form})

class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('home:index')

class IndexView(LoginRequiredMixin, View):
    template_name = 'accounts/index.html'   
    title = 'Moje konto | '               

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': self.title})

class ChangeEmailView(LoginRequiredMixin, View):
    template_name = 'accounts/change-email.html'   
    title = 'Zmień email | Moje konto | '                           

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': self.title, 'form': UserChangeEmailForm({'email': request.user.email}, request=request)})

    def post(self, request, *args, **kwargs):
        form = UserChangeEmailForm(request.POST, request=request)
        if form.is_valid():
            user = User.objects.get(username = request.user.username)
            user.email = form.cleaned_data['email']
            user.save()
            login(request, user)
            return redirect('accounts:index')
        else:
            return render(request, self.template_name, {'title': self.title, 'form': form})

class ChangePasswordView(LoginRequiredMixin, View):
    template_name = 'accounts/change-password.html'   
    title = 'Zmień hasło | Moje konto | '                          

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': self.title, 'form': UserChangePasswordForm(request=request)})

    def post(self, request, *args, **kwargs):
        form = UserChangePasswordForm(request.POST, request=request)
        if form.is_valid():
            user = User.objects.get(username = request.user.username)
            user.set_password(form.cleaned_data['newPassword'])
            user.save()
            login(request, user)
            return redirect('accounts:index')
        else:
            return render(request, self.template_name, {'title': self.title, 'form': form})

class ChangePersonalDataView(LoginRequiredMixin, View):
    template_name = 'accounts/change-personal-data.html'   
    title = 'Zmień dane personalne | Moje konto | '    

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': self.title, 'form': UserChangePersonalDataForm({'first_name': request.user.first_name, 'last_name': request.user.last_name})})

    def post(self, request, *args, **kwargs):
            form = UserChangePersonalDataForm(request.POST)
            if form.is_valid():
                user = User.objects.get(username = request.user.username)
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
                login(request, user)
                return redirect('accounts:index')
            else:
                return render(request, self.template_name, {'title': self.title, 'form': form})

src/accounts/templates/accounts/change-email.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        {% include 'accounts/link/index.html' %}
        <span class='nav_text'>Zmień email</span>
    </nav>

    <div class='flex-100'>
    <form class='my_form' action='{% url 'accounts:change-email' %}' method='POST'>
        {% csrf_token %}
        <h1>Zmień email</h1>
        <h2>Wprowadź nowe dane</h2>
        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Zapisz'></p>
    </form>
    </div>
{% endblock content %}

src/accounts/templates/accounts/change-password.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        {% include 'accounts/link/index.html' %}
        <span class='nav_text'>Zmień hasło</span>
    </nav>

    <div class='flex-100'>
    <form class='my_form' action='{% url 'accounts:change-password' %}' method='POST'>
        {% csrf_token %}
        <h1>Zmień hasło</h1>
        <h2>Wprowadź nowe dane</h2>
        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Zapisz'></p>
    </form>
    </div>
{% endblock content %}

src/accounts/templates/accounts/change-personal-data.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        {% include 'accounts/link/index.html' %}
        <span class='nav_text'>Zmień dane personalne</span>
    </nav>

    <div class='flex-100'>
    <form class='my_form' action='{% url 'accounts:change-personal-data' %}' method='POST'>
        {% csrf_token %}
        <h1>Zmień dane personalne</h1>
        <h2>Wprowadź nowe dane</h2>
        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Zapisz'></p>
    </form>
    </div>
{% endblock content %}

src/accounts/templates/accounts/index.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        <span class='nav_text'>Moje konto</span>
    </nav>

    <div class='flex-100'>
        <h1>Moje konto 
        {% if user.is_superuser %}- <span class='info'>administrator</span>{% endif %}
        {% if not user.is_superuser and user.is_staff %}- <span class='info'>pracownik</span>{% endif %}
        </h1>
        <h3>
            Nazwa użytkownika: <span class='info'>{{ request.user.username }} </span>
        </h3>
        <h3>
            Adres email: <span class='info'>{{ request.user.email }}</span> 
            <a href='{% url 'accounts:change-email' %}' class='button_link'>Zmień adres email</a>
        </h3>
        <h3>Hasło: <span class='info'> ********** </span> 
        <a href='{% url 'accounts:change-password' %}' class='button_link'>Zmień hasło</a>
        <h3>
            Imię i nazwisko: <span class='info'>{{ request.user.first_name }} {{ request.user.last_name }}</span>
            <a href='{% url 'accounts:change-personal-data' %}' class='button_link'>Zmień dane personalne</a>
        </h3>
        <br>
        <h3>Data ostatniego logowania: <span class='info'>{{ request.user.last_login }}</span></h3>
        <h3>Data utworzenia konta: <span class='info'>{{ request.user.date_joined }}</span></h3>
        
    </div>
{% endblock content %}

src/accounts/templates/accounts/login.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        <span class='nav_text'>Logowanie</span>
    </nav>

    <div class='flex-100'>
    <form class='my_form' action='{% url 'accounts:login' %}' method='POST'>
        {% csrf_token %}
        <h1>Logowanie</h1>
        <h2>Wprowadź dane logowania</h2>
        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Zaloguj'></p>
        <p><a href='{% url 'accounts:register' %}'>Nie masz konta? Zarejestruj się</a></p>
        <input type='hidden' name='next' value='{{ next }}'>
    </form>
    </div>
{% endblock content %}

src/accounts/templates/accounts/register.html
{% extends 'base/index.html' %} 

{% block content %}             
    <nav class='flex-100'>
        {% block navlink %} {% endblock navlink %}
        {% include 'home/link/index.html' %}
        <span class='nav_text'>Rejestracja</span>
    </nav>

    <div class='flex-100'>
    <form class='my_form' action='{% url 'accounts:register' %}' method='POST'>
        {% csrf_token %}
        <h1>Rejestracja</h1>
        <h2>Wprowadź dane nowego użytkownika</h2>
        {{ form.as_p }}
        <p><input id='submit' type='submit' value='Utwórz konto'></p>
        <p><a href='{% url 'accounts:login' %}'>Masz już konto? Zaloguj się</a></p>
    </form>
    </div>
{% endblock content %}